using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using TMPro;
using System.Collections;



public class GameModeHandler : MonoBehaviour
{
    public GameObject missionUI;
    public TMP_Text missionTimerText; 
    public float missionTime = 10f;

    public GameObject victoryCanvas;

    public AudioSource clapAudio;

    private bool hasWon = false;

    void Start()
    {
        Debug.Log("âœ… GameModeHandler Started");

        switch (GameModeManager.SelectedMode)
        {
            case GameModeManager.GameMode.Easy:
                SetEasyMode();
                break;
            case GameModeManager.GameMode.Hard:
                SetHardMode();
                break;
            case GameModeManager.GameMode.Mission:
                SetMissionMode();
                break;
        }
    }

    void Update()
    {
        
        if (GameModeManager.SelectedMode == GameModeManager.GameMode.Mission)
        {
            missionTime -= Time.deltaTime;

            if (missionTimerText != null)
                missionTimerText.text = "Time: " + Mathf.Ceil(missionTime).ToString();


            if (missionTime <= 1 &&!hasWon)
            {
                hasWon = true;
                StartCoroutine(HandleVictory());   

                Debug.Log("ðŸŽ‰ Mission Complete! Victory Canvas shown.");

            }
        }
    }
    IEnumerator HandleVictory()
{
    GameObject player = GameObject.FindGameObjectWithTag("Player");
if (player != null)
    player.SetActive(false);

    if (clapAudio != null)
    {
    clapAudio.PlayOneShot(clapAudio.clip);
        Debug.Log("ðŸ”Š Clap Audio Played");
    }
    Debug.Log("ðŸ HandleVictory() Started");

    if (missionUI != null)
        missionUI.SetActive(false);

    if (victoryCanvas != null)
        victoryCanvas.SetActive(true);


    // Ù†Ù†ØªØ¸Ø± Ø¹Ø´Ø§Ù† ÙŠØ´ØªØºÙ„ Ø§Ù„ØµÙˆØª ÙƒØ§Ù…Ù„
    yield return new WaitForSecondsRealtime(5f);

    // Ù†ÙˆÙ‚Ù Ø§Ù„Ù„Ø¹Ø¨Ø© Ø¨Ø¹Ø¯ Ø§Ù„ØµÙˆØª
    Debug.Log("ðŸ›‘ Game Paused");
}


    void SetEasyMode()
    {
        Time.timeScale = 1f;
        if (missionUI != null) missionUI.SetActive(false);
        if (victoryCanvas != null) victoryCanvas.SetActive(false);
    }

    void SetHardMode()
    {
        Time.timeScale = 1f;
        if (missionUI != null) missionUI.SetActive(false);
        if (victoryCanvas != null) victoryCanvas.SetActive(false);
    }

    void SetMissionMode()
    {
        Time.timeScale = 1f;
        if (missionUI != null) missionUI.SetActive(true);
        if (victoryCanvas != null) victoryCanvas.SetActive(false);
    }

}
